name: All

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: "all"
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y llvm-dev libclang-dev clang
      - name: Install rust
        uses: moonrepo/setup-rust@v1
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build project
        run: cargo build
      - name: Test project
        run: cargo test
      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v5
      - name: Create documents
        if: github.ref == 'refs/heads/main'
        run: cargo doc --no-deps
      - name: Upload documents artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: './target/doc/'
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Login to Github registry
        # if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker images
        run: |
          docker build . --tag ghcr.io/${{ github.repository }}/journal-sdk:latest
          docker build . --tag ghcr.io/${{ github.repository }}/journal-sdk:$( cargo pkgid | cut -d '@' -f 2 )
      - name: Push Docker images
        # if: github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/${{ github.repository }}/journal-sdk:latest
          docker push ghcr.io/${{ github.repository }}/journal-sdk:$( cargo pkgid | cut -d '@' -f 2 )
