name: Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: "build"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CARGO_HOME: ${{ github.workspace }}
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y llvm-dev libclang-dev clang
      - name: Install rust
        uses: moonrepo/setup-rust@v1
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build project
        run: |
          cargo build --release
      - name: Calculate version number
        run: |
          echo $( cargo pkgid )
          mkdir -p .ci-cd
          cargo pkgid | cut -d '@' -f 2 > .ci-cd/version.txt
      - name: Upload cargo
        uses: actions/upload-artifact@v4
        with:
          name: cargo
          path: .cargo
      - name: Upload target
        uses: actions/upload-artifact@v4
        with:
          name: target
          path: target
      - name: Upload CI/CD
        uses: actions/upload-artifact@v4
        with:
          name: ci-cd
          path: .ci-cd
