name: Container

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]
  workflow_run:
    workflows: [ "Build" ]
    types:
      - completed

concurrency:
  group: "container"
  cancel-in-progress: false

jobs:
  containerize:
    # if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Login to Github registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download CI/CD
        uses: actions/download-artifact@v4
        with:
          name: ci-cd
      - name: Build Docker image
        run: |
          docker build . --tag ghcr.io/${{ github.repository }}/journal-sdk:latest
          docker build . --tag ghcr.io/${{ github.repository }}/journal-sdk:$( cat .ci-cd/version.txt )
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/journal-sdk:latest
          docker push ghcr.io/${{ github.repository }}/journal-sdk:$( cat .ci-cd/version.txt )
