name: Container

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Github registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag journal-sdk:$(date +%s)
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}/journal-sdk:latest
