name: Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: "test"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y llvm-dev libclang-dev clang
    - name: Install rust
      uses: moonrepo/setup-rust@v1
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run unit tests
      run: |
        cargo test
