name: Test

on:
  workflow_run:
    workflows: [ "Build" ]
    types:
      - completed

concurrency:
  group: "test"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y llvm-dev libclang-dev clang
      - name: Install rust
        uses: moonrepo/setup-rust@v1
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download cargo
        uses: actions/download-artifact@v4
        with:
          name: cargo
      - name: Download target
        uses: actions/download-artifact@v4
        with:
          name: target
      - name: Run unit tests
        run: |
          cargo test
